### ISSUE TITLE
502 error when submitting a new event

### ISSUE THREAD

**Issue by djanek** [johnpolacek/chicagotechevents.com#187]
Hi John, love the site!

Not sure where you prefer to receive these types of bugs/issues, couldn't find a support link/email on the site, so I figured I might as well just log it here.

When submitting a new event I'm currently getting a 502 error from netlify (see screenshot).

Screenshot: https://pasteboard.co/InuieRA.jpg

**Comment by johnpolacek** [comment]
@djanek  I've made some changes. Can you try again?

**Comment by johnpolacek** [comment]
Haven't heard any other reports of this. Closing.
